
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  {{- if not (eq .Values.global.protocol "http") }}
  - secretName: {{ .Values.global.domain }}
    hosts:
    - {{ .Values.global.domain }}
  {{- end }}
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /404
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
