enabled: true
global:
  development: false
  protocol: https
replicaCount: 1
website: http://countdown.stream.place.s3-website-us-west-2.amazonaws.com/from/now
image:
  repository: streamplace/sp-compositor
  pullPolicy: Always
service:
  name: sp-compositor
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
  - host: sp-dev.club
    path: /demo/countdown
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
