# Default values for streamkitchen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  development: true
  # Replace this with the path to your streamplace repo
  rootDirectory: /Users/example/git/streamplace
  # Your email goes here!
  adminEmail: admin@example.com
  # In case you want to push your own images, this could be set to something else.
  repo: stream.place
  domain: localhost
  protocol: http
  jwt:
    audience: hZU06VmfYz2JLZCkjtJ7ltEy5SOsvmBA
    secret: QjAzNEMwMEUtQkY5Qi00OTQyLUJEQUEtMEYxNEZENUVERERE
    # If someone hasn't logged in for this long, they won't be.
    expiration: 30d
  plugins:
    - sp-plugin-core
  authIssuer: 'https://streamkitchen.auth0.com/'
  externalIP: "0.0.0.0"
  s3:
    accessKeyId: DEV_ACCESS_KEY
    secretAccessKey: DEV_SECRET_KEY
    host: http://dev-sp-file-server.default.svc.cluster.local
    bucket: dev-files

# This exposes the correct ports on Kube for Docker for Desktop
sp-ingress:
  serviceType: LoadBalancer

# Disable lots of features that we don't need in dev

# we use local frontends 'cause doing it in kube sucks
sp-frontend:
  enabled: false

sp-registry:
  enabled: false

sp-redirects:
  enabled: false

sp-auth-frontend:
  enabled: false

sp-kube-lego:
  enabled: false

# don't want the demo in dev...
sp-compositor:
  enabled: false

sp-file-server:
  enabled: true
