apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-tcp
data:
  1935: "{{ .Release.Namespace }}/{{ .Release.Name }}-sp-rtmp-server:1935"
  8008: "{{ .Release.Namespace }}/{{ .Release.Name }}-sp-scuttlebot:8008"
