# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    macos:
      xcode: "9.2.0"

    steps:
      - checkout

      # - run:
      #     name: install node
      #     command: brew install node

      # Build the app and run tests
      - run:
          name: build app
          command: npm run ci:build-app


      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      # - store_test_results:
      #     path: test_output/report.xml
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: scan-test-results
      # - store_artifacts:
      #     path: ~/Library/Logs/scan
      #     destination: scan-logs
