apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "sp-scuttlebot.fullname" . }}
  labels:
    app: {{ template "sp-scuttlebot.name" . }}
    chart: {{ template "sp-scuttlebot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "sp-scuttlebot.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sp-scuttlebot.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: data
        {{- if .Values.persistence }}
{{ .Values.persistence | toYaml | indent 10 }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - scuttlebot
            - server
            - --allowPrivate
            - --host
            - {{ index .Values.ingress.hosts 0 | quote }}
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
