apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "sp-compositor.fullname" . }}
  labels:
    app: {{ template "sp-compositor.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "sp-compositor.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.global.development }}
          image: "{{ .Values.global.repo }}/{{ .Chart.Name }}:latest"
          {{- else }}
          image: "{{ .Values.global.repo }}/{{ .Chart.Name }}:{{ .Chart.Version }}"
          {{- end }}
          imagePullPolicy: {{ if .Values.global.development }}Never{{ else }}Always{{ end }}
          env:
            - name: PORT
              value: {{ .Values.service.internalPort | quote }}
            - name: WEBSITE
              value: {{ .Values.website }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /manifest.mpd
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /manifest.mpd
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
