apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: local-logger
  namespace: kube-system
  labels:
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        app: local-logger
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: elk
        image: streamplace/elk-logtrail:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5601
            hostPort: 5601
          - containerPort: 9200
            hostPort: 9200
          - containerPort: 5044
            hostPort: 5044
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:elasticsearch
        imagePullPolicy: IfNotPresent
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "localhost"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

---

apiVersion: v1
kind: Service
metadata:
  name: local-logger
  namespace: kube-system
spec:
  type: LoadBalancer
  selector:
    app: local-logger
  ports:
    - name: http
      port: 5601
      protocol: TCP
      targetPort: 5601
