
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-body-size: 4096m
spec:
  {{- if not (eq .Values.global.protocol "http") }}
  tls:
  - secretName: {{ .Values.global.domain }}
    hosts:
    - {{ .Values.global.domain }}
  {{- end }}
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /upload
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
