
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "sp-registry.fullname" . }}
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    proxy:
      remoteurl: https://quay.io/streamplace
    http:
      addr: :80
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
